#! /bin/sh

~/.config/polybar/polybar.sh &

feh --randomize --bg-fill ~/.Wallpapers/

sxhkd &
xbindkeys &
wmname LG3D

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         4
bspc config window_gap           5
bspc config top_padding          0 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d8dee8"
bspc config normal_border_color  "#2f343f"
bspc config presel_feedback_color "#ff5c57"

bspc rule -a slack desktop='^1' focus=on 
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a goland desktop='^3' focus=on
bspc rule -a webstorm desktop='^3' focus=on 
bspc rule -a telegram desktop='^5' focus=on state=tiled 
bspc rule -a telegram-desktop desktop='^5' focus=on state=tiled 
bspc rule -a 'telegram desktop' desktop='^5' focus=on state=tiled 
bspc rule -a telegramDesktop desktop='^5' focus=on state=tiled 
bspc rule -a standard-notes desktop='^6' focus=on state=tiled 
bspc rule -a 'standard notes' desktop='^6' focus=on state=tiled 
bspc rule -a 'standardNotes' desktop='^6' focus=on state=tiled 
bspc rule -a notes desktop='^6' focus=on state=tiled 
bspc rule -a vlc desktop='^4' follow=on focus=on
bspc rule -a qpicview state=floating follow=on
bspc rule -a ffplay state=floating sticky=on

# Compton
if [ -x "$(command -v picom)" ]
  bspc rule -a webstorm desktop='^3' focus=on state=tiled 
  bspc rule -a webstorm desktop='^3' focus=on state=tiled 
  bspc rule -a webstorm desktop='^3' focus=on state=tiled 
  bspc rule -a webstorm desktop='^3' focus=on state=tiled 
then
    killall picom;picom -b --dbus
elif [ -x "$(command -v compton)" ]
then
    killall compton;compton --config ~/.config/compton/compton.conf -b --dbus
fi

# Set Cursor
xsetroot -cursor_name left_ptr

firefox &
dunst &
urxvtd &
telegram-dekstop &
notes &
light-locker --lock-on-suspend --lock-on-lid &
unclutter --timeout 1 --fork & 
ldm -u freak -p /mnt &
redshift &


#setxkbmap -option caps:escape
