require("myrc.run_once")
local awful = require("awful")
run_once("nextcloud")
run_once("firefox")
run_once("telegram-desktop")
run_once("notes")
run_once("urxvtd")
run_once("xbindkeys")
run_once("unclutter --timeout 1 --fork --ignore-scrolling --jitter 20")
run_once("light-locker --lock-on-suspend --lock-on-lid --lock-after-screensaver=10")
